name: Train ML model with MLflow

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          environment-file: MLProject/conda.yaml
          activate-environment: rf_env

      - name: Install MLflow
        run: pip install mlflow

      - name: Train model via MLflow Project
        run: |
          mlflow run ./MLProject -P data_path=heart_processed.csv
