name: Train ML model with MLflow

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Setup Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Setup Miniconda and activate environment
        uses: conda-incubator/setup-miniconda@v2
        with:
    
          auto-activate-base: false
          environment-file: Workflow-CI/MLProject/conda.yaml
          activate-environment: rf_env
          miniforge-version: latest
          mamba-version: "*"


      - name: Train model via MLflow Project
        run: |
          mlflow run ./Workflow-CI/MLProject -P data_path=heart_processed.csv
