name: Train ML model with MLflow

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7 
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m venv .venv                         # Membuat virtual environment bernama '.venv'
          source .venv/bin/activate                     # Mengaktifkan virtual environment
          pip install --upgrade pip                     # Memastikan pip terbaru
          pip install -r Workflow-CI/MLProject/requirements.txt # Menginstal dependensi dari file Anda

      - name: Train model via MLflow Project
        run: |
          source .venv/bin/activate # Mengaktifkan kembali virtual environment untuk langkah ini
          mlflow run ./Workflow-CI/MLProject/ -P data_path=heart_processed.csv
